import 'package:flutter/material.dart';
import 'package:persian_calendar_widget/core/data/enums/calendar_type.dart';
import 'package:persian_calendar_widget/core/data/enums/first_day_of_week.dart';
import 'package:persian_calendar_widget/core/data/enums/pick_date_format.dart';
import 'package:persian_calendar_widget/core/data/i18n/i18n.dart';
import 'package:persian_calendar_widget/feature/feature_dialog_box/date_picker_dialog_box.dart';
import 'package:persian_calendar_widget/feature/feature_dialog_box/date_picker_dialog_box_without_day.dart';

class MinimalPersianCalendar {
  static void pickDay({
    required BuildContext context,
    required OnPickDate? onSubmit,
    required CalendarType calendarType,
    DateTime? initialDate,
    double? borderRadius,
    Color? primaryColor,
    Color? onPrimaryColor,
    Color? background,
    TextStyle? titleTextStyle,
    TextStyle? titleSelectedTextStyle,
    TextStyle? dateTextStyle,
    TextStyle? dateSelectedTextStyle,
    TextStyle? submitTextStyle,
    TextStyle? cancelTextStyle,
    @Deprecated('Use I18nButtons() instead') String? submitTitle,
    @Deprecated('Use I18nButtons() instead') String? cancelTitle,
    bool? showTodayBanner,
    TextStyle? todayDateBannerTextStyle,
    bool? useGoToTodayButton,
    @Deprecated('Use I18nButtons() instead') String? goTitle,
    TextStyle? goTextStyle,
    EdgeInsetsGeometry? weekDaysPadding,
    TextStyle? weekDaysTextStyle,
    FirstDayOfWeek? firstDayOfWeek,
    I18n? i18n,
    bool? enablePersianDigits,
  }) {
    showDialog(
      context: context,
      builder: (context) {
        return DatePickerDialogBox(
          initialDate: initialDate,
          onSubmit: onSubmit,
          borderRadius: borderRadius ?? 20.0,
          pickDateFormat: PickDateFormat.dd,
          maxYear: null,
          minYear: null,
          background: background,
          onPrimaryColor: onPrimaryColor,
          primaryColor: primaryColor,
          cancelButtonStyle: null,
          cancelTextStyle: cancelTextStyle,
          cancelTitle: cancelTitle,
          submitButtonStyle: null,
          submitTextStyle: submitTextStyle,
          submitTitle: submitTitle,
          dateButtonStyle: null,
          dateSelectedButtonStyle: null,
          dateSelectedTextStyle: dateSelectedTextStyle,
          dateTextStyle: dateTextStyle,
          titleBoxStyle: null,
          titleButtonStyle: null,
          titleSelectedButtonStyle: null,
          titleSelectedTextStyle: titleSelectedTextStyle,
          titleTextStyle: titleTextStyle,
          calendarType: calendarType,
          showTodayBanner: showTodayBanner ?? false,
          todayDateBannerTextStyle: todayDateBannerTextStyle,
          useGoToTodayButton: useGoToTodayButton ?? false,
          goTitle: goTitle,
          goButtonStyle: null,
          goTextStyle: goTextStyle,
          weekDaysBoxStyle: null,
          weekDaysPadding: weekDaysPadding,
          weekDaysTextStyle: weekDaysTextStyle,
          firstDayOfWeek: firstDayOfWeek,
          i18n: i18n,
          enablePersianDigits: enablePersianDigits ?? true,
        );
      },
    );
  }

  static void pickMonthAndDay({
    required BuildContext context,
    required OnPickDate? onSubmit,
    required CalendarType calendarType,
    DateTime? initialDate,
    double? borderRadius,
    Color? primaryColor,
    Color? onPrimaryColor,
    Color? background,
    TextStyle? titleTextStyle,
    TextStyle? titleSelectedTextStyle,
    TextStyle? dateTextStyle,
    TextStyle? dateSelectedTextStyle,
    TextStyle? submitTextStyle,
    TextStyle? cancelTextStyle,
    @Deprecated('Use I18nButtons() instead') String? submitTitle,
    @Deprecated('Use I18nButtons() instead') String? cancelTitle,
    bool? showTodayBanner,
    TextStyle? todayDateBannerTextStyle,
    bool? useGoToTodayButton,
    @Deprecated('Use I18nButtons() instead') String? goTitle,
    TextStyle? goTextStyle,
    EdgeInsetsGeometry? weekDaysPadding,
    TextStyle? weekDaysTextStyle,
    FirstDayOfWeek? firstDayOfWeek,
    I18n? i18n,
    bool? enablePersianDigits,
  }) {
    showDialog(
      context: context,
      builder: (context) {
        return DatePickerDialogBox(
          initialDate: initialDate,
          onSubmit: onSubmit,
          borderRadius: borderRadius ?? 20.0,
          pickDateFormat: PickDateFormat.ddMM,
          maxYear: null,
          minYear: null,
          background: background,
          onPrimaryColor: onPrimaryColor,
          primaryColor: primaryColor,
          cancelButtonStyle: null,
          cancelTextStyle: cancelTextStyle,
          cancelTitle: cancelTitle,
          submitButtonStyle: null,
          submitTextStyle: submitTextStyle,
          submitTitle: submitTitle,
          dateButtonStyle: null,
          dateSelectedButtonStyle: null,
          dateSelectedTextStyle: dateSelectedTextStyle,
          dateTextStyle: dateTextStyle,
          titleBoxStyle: null,
          titleButtonStyle: null,
          titleSelectedButtonStyle: null,
          titleSelectedTextStyle: titleSelectedTextStyle,
          titleTextStyle: titleTextStyle,
          calendarType: calendarType,
          showTodayBanner: showTodayBanner ?? false,
          todayDateBannerTextStyle: todayDateBannerTextStyle,
          useGoToTodayButton: useGoToTodayButton ?? false,
          goTitle: goTitle,
          goButtonStyle: null,
          goTextStyle: goTextStyle,
          weekDaysBoxStyle: null,
          weekDaysPadding: weekDaysPadding,
          weekDaysTextStyle: weekDaysTextStyle,
          firstDayOfWeek: firstDayOfWeek,
          i18n: i18n,
          enablePersianDigits: enablePersianDigits ?? true,
        );
      },
    );
  }

  static void pickFullDate({
    required BuildContext context,
    required OnPickDate? onSubmit,
    required CalendarType calendarType,
    DateTime? initialDate,
    int? maxYear,
    int? minYear,
    double? borderRadius,
    Color? primaryColor,
    Color? onPrimaryColor,
    Color? background,
    TextStyle? titleTextStyle,
    TextStyle? titleSelectedTextStyle,
    TextStyle? dateTextStyle,
    TextStyle? dateSelectedTextStyle,
    TextStyle? submitTextStyle,
    TextStyle? cancelTextStyle,
    @Deprecated('Use I18nButtons() instead') String? submitTitle,
    @Deprecated('Use I18nButtons() instead') String? cancelTitle,
    bool? showTodayBanner,
    TextStyle? todayDateBannerTextStyle,
    bool? useGoToTodayButton,
    @Deprecated('Use I18nButtons() instead') String? goTitle,
    TextStyle? goTextStyle,
    EdgeInsetsGeometry? weekDaysPadding,
    TextStyle? weekDaysTextStyle,
    FirstDayOfWeek? firstDayOfWeek,
    I18n? i18n,
    bool? enablePersianDigits,
  }) {
    showDialog(
      context: context,
      builder: (context) {
        return DatePickerDialogBox(
          initialDate: initialDate,
          onSubmit: onSubmit,
          borderRadius: borderRadius ?? 20.0,
          pickDateFormat: PickDateFormat.ddMMyyyy,
          maxYear: maxYear,
          minYear: minYear,
          background: background,
          onPrimaryColor: onPrimaryColor,
          primaryColor: primaryColor,
          cancelButtonStyle: null,
          cancelTextStyle: cancelTextStyle,
          cancelTitle: cancelTitle,
          submitButtonStyle: null,
          submitTextStyle: submitTextStyle,
          submitTitle: submitTitle,
          dateButtonStyle: null,
          dateSelectedButtonStyle: null,
          dateSelectedTextStyle: dateSelectedTextStyle,
          dateTextStyle: dateTextStyle,
          titleBoxStyle: null,
          titleButtonStyle: null,
          titleSelectedButtonStyle: null,
          titleSelectedTextStyle: titleSelectedTextStyle,
          titleTextStyle: titleTextStyle,
          calendarType: calendarType,
          showTodayBanner: showTodayBanner ?? false,
          todayDateBannerTextStyle: todayDateBannerTextStyle,
          useGoToTodayButton: useGoToTodayButton ?? false,
          goTitle: goTitle,
          goButtonStyle: null,
          goTextStyle: goTextStyle,
          weekDaysBoxStyle: null,
          weekDaysPadding: weekDaysPadding,
          weekDaysTextStyle: weekDaysTextStyle,
          firstDayOfWeek: firstDayOfWeek,
          i18n: i18n,
          enablePersianDigits: enablePersianDigits ?? true,
        );
      },
    );
  }

  static void pickYearAndMonth({
    required BuildContext context,
    required OnPickDateWithoutDay? onSubmit,
    required CalendarType calendarType,
    DateTime? initialDate,
    int? maxYear,
    int? minYear,
    double? borderRadius,
    Color? primaryColor,
    Color? onPrimaryColor,
    Color? background,
    TextStyle? titleTextStyle,
    TextStyle? titleSelectedTextStyle,
    TextStyle? dateTextStyle,
    TextStyle? dateSelectedTextStyle,
    TextStyle? submitTextStyle,
    TextStyle? cancelTextStyle,
    @Deprecated('Use I18nButtons() instead') String? submitTitle,
    @Deprecated('Use I18nButtons() instead') String? cancelTitle,
    bool? showTodayBanner,
    TextStyle? todayDateBannerTextStyle,
    bool? useGoToTodayButton,
    @Deprecated('Use I18nButtons() instead') String? goTitle,
    TextStyle? goTextStyle,
    I18n? i18n,
    bool? enablePersianDigits,
  }) {
    showDialog(
      context: context,
      builder: (context) {
        return DatePickerDialogBoxWithoutDay(
          initialDate: initialDate,
          onSubmit: onSubmit,
          borderRadius: borderRadius ?? 20.0,
          maxYear: maxYear,
          minYear: minYear,
          background: background,
          onPrimaryColor: onPrimaryColor,
          primaryColor: primaryColor,
          cancelButtonStyle: null,
          cancelTextStyle: cancelTextStyle,
          cancelTitle: cancelTitle,
          submitButtonStyle: null,
          submitTextStyle: submitTextStyle,
          submitTitle: submitTitle,
          dateButtonStyle: null,
          dateSelectedButtonStyle: null,
          dateSelectedTextStyle: dateSelectedTextStyle,
          dateTextStyle: dateTextStyle,
          titleBoxStyle: null,
          titleButtonStyle: null,
          titleSelectedButtonStyle: null,
          titleSelectedTextStyle: titleSelectedTextStyle,
          titleTextStyle: titleTextStyle,
          calendarType: calendarType,
          showTodayBanner: showTodayBanner ?? false,
          todayDateBannerTextStyle: todayDateBannerTextStyle,
          useGoToTodayButton: useGoToTodayButton ?? false,
          goTitle: goTitle,
          goButtonStyle: null,
          goTextStyle: goTextStyle,
          firstDayOfWeek: null,
          i18n: i18n,
          enablePersianDigits: enablePersianDigits ?? true,
        );
      },
    );
  }
}
